theme: jekyll-theme-cayman
layout: page
title: "NETN FOM"
description: "NATO Education and Training Network (NETN) Federation Object Model (FOM)"
download_url: https://github.com/AMSP-04/NETN-FOM/releases/tag/v3.0-rc1
repo_url: https://github.com/AMSP-04/
